### ISSUE TITLE
Would be nice to have the ability for multiple override files

### ISSUE THREAD

**Issue by jmalouf69** [djhaskin987/terraform-provider-helmcmd#1]

**Comment by djha-skin** [comment]
Hi jmalouf! Sorry I didn't see this ticket earlier.

While this would be nice, it's sort of a limitation of the design that we can't have multiple override files. If you did this, it would cause the "lifecycle-ness" of the helm resource to break down. That is to say, I need to be able to specify overrides and *also* read them using helm get overrides in sort of a uniform way.

You can do something like this, though, with terraform's file templating. Sorry I wasn't more helpful!
