### ISSUE TITLE
Please add `timeout` and `tiller-timeout`

### ISSUE THREAD

**Issue by djha-skin** [djhaskin987/terraform-provider-helmcmd#3]
Please add `timeout` and `tiller_timeout` attributes to the Provider block, ensuring that helm can get called with different timeout and `--tiller-timeout` options. Per Satya Alla from SlingTV

**Comment by salla2** [comment]
@djhaskin987 any update on timeout option? Thanks in advance!

**Comment by djha-skin** [comment]
Done, take it for a spin and let me know if you have problems: https://github.com/djhaskin987/terraform-provider-helmcmd/releases/tag/v0.4.0
