### ISSUE TITLE
Namespace update should trigger the release delete & create

### ISSUE THREAD

**Issue by legal90** [djhaskin987/terraform-provider-helmcmd#6]
Hi! 
Thank you for this project. The provider looks interesting, so I wanted to try it, but found an issue with some field updates.

Currently if the field `namespace` is changed in the Terraform configuration, the provider shows that it could be updated:
```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ helmcmd_release.overprovisioning
      namespace: "overprovisioning" => "default"


Plan: 0 to add, 1 to change, 0 to destroy.
```
It even tries to apply this change by running `helm` with a new namespace. However, it doen't take any effect because `helm` still uses the old one:
```
2018-09-21T17:07:42.623+0200 [DEBUG] plugin.terraform-provider-helmcmd: WARNING: Namespace "default" doesn't match with previous. Release will be deployed to overprovisioning
```

We get a situation when terraform successfully applies the change, but the state is not changed, so it shows the `update in-place` every time we run ` terraform plan` or `terraform apply`.

I guess, the expected behavior would be if the provider treats `namespace` as "not-updatable", so it will delete a release and create a new one.

**Comment by djha-skin** [comment]
Thanks for bringing this up, I'll take care of it.

**Comment by djha-skin** [comment]
Done, take it for a spin and let me know if you have problems: https://github.com/djhaskin987/terraform-provider-helmcmd/releases/tag/v0.4.0

**Comment by legal90** [comment]
@djhaskin987 Yes, the issue looks fixed now. Thank you so much for the quick fix! 👍
